# Generated by Django 5.1.4 on 2025-02-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('tirada', models.IntegerField(blank=True, default=1, null=True)),
                ('qiimaha_soo_iibsiga', models.FloatField(blank=True, null=True)),
                ('qiimaha_iska_iibinta', models.FloatField(blank=True, null=True)),
                ('kharashaadka', models.FloatField(blank=True, null=True)),
                ('dakhliga', models.FloatField(blank=True, null=True)),
                ('faa_iido', models.FloatField(blank=True, null=True)),
                ('faa_iidada_percent', models.FloatField(blank=True, null=True)),
                ('khasaaro', models.FloatField(blank=True, null=True)),
                ('khasaaro_percent', models.FloatField(blank=True, null=True)),
                ('dakhliga_hadda', models.FloatField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
